name: setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "18"
    - run: npm i
      shell: bash
    - run: npm run build
      shell: bash
    - run: echo "VERSION=$(node -p "require('./package.json').version")" >> "$GITHUB_ENV"
      shell: bash
